### ISSUE TITLE
Rails query generator not found

### ISSUE THREAD

**Issue by Joseph-Burke** [rootstrap/arqo#18]
## Bug report:
* **Expected Behavior**: 
`rails generate query [e.g. User]` should generate a UserQuery object in `app/queries`. 
`rails generate --help` should confirm the existence of the query generator
* **Actual Behavior**: 
`bundle exec rails generate query User` => `Could not find generator 'query'.`
`rails generate --help | grep query` shows nothing
* **Steps to Reproduce**: 
  1. Create or open a Rails 6 application
  2. Install the gem using `bundle add arqo` or `gem install arqo`
  3. Run `rails generate query [e.g. User]`

* **Version of the repo**:
0.2.0
* **Ruby and Rails Version**: 
Ruby 2.6.3
Rails 6.0.0

**Comment by santib** [comment]
Hey @Joseph-Burke thanks for the detailed report! I think #19 fixes it in case you want to try it out

**Comment by Joseph-Burke** [comment]
Thank you!
