### ISSUE TITLE
Compatibility with Rails 7

### ISSUE THREAD

**Issue by Joseph-Burke** [rootstrap/arqo#22]
Just tried adding arqo to a Rails 7 app but found that arqo 0.2.0 depends on ActiveRecord (< 7.0.0).

Really love this gem so would love to see it become compatible with the latest version of Rails in the future!

```
% bundle add arqo
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Bundler could not find compatible versions for gem "activerecord":
  In snapshot (Gemfile.lock):
    activerecord (= 7.0.3.1)

  In Gemfile:
    activerecord-postgis-adapter (~> 8.0) was resolved to 8.0.1, which depends on
      activerecord (~> 7.0.0)

    arqo was resolved to 0.2.0, which depends on
      activerecord (< 7, >= 4)

Deleting your Gemfile.lock file and running `bundle install` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by santib** [comment]
Hi @Joseph-Burke I just published `v0.3.0` which supports Rails 7. Glad to find out you like the gem, and please let me know if you find any issue. Thanks!

https://github.com/rootstrap/arqo/releases/tag/v0.3.0
https://rubygems.org/gems/arqo/versions/0.3.0
